# -*- coding: utf-8 -*-
"""Basic Cryptography-Hash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u2VjTrZPfJ50OWXsUS1tV_VlZC_tKZKn
"""

import hashlib

h = hashlib.new('SHA256')

password = '225444777788655618'

h.update(password.encode())

password_hash = h.hexdigest()
print(password_hash)

