# -*- coding: utf-8 -*-
"""Basic Cryptography-encrypt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uB7ps3iHFc_SKb1dYnuoy01UQvt0__M
"""

print('Hello World')

name = 'สมชาย'
lastname = 'ดีมาก'
fullname = name +' '+ lastname

print(fullname)

!pip install cryptography

from cryptography.fernet import Fernet

key = Fernet.generate_key()
print(key)

f = Fernet(key)

text = 'คุณเข้ารหัสได้แล้ว! สุดยอด'

message = f.encrypt(text.encode('utf-8'))
print(message)
print(message.decode('utf-8'))

